# Generated by Django 5.2 on 2025-04-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_person_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, default='default_profile_pic.jpg', null=True, upload_to='photos/'),
        ),
    ]
